# Generated by Django 5.2.17 on 2026-09-26 07:03

import care.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('vet', 'Veterinary care'), ('groomer', 'Grooming'), ('boarding', 'Boarding & day care'), ('sitter', 'Sitters & walkers'), ('trainer', 'Training'), ('shop', 'Pet supplies'), ('other', 'Other care')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('hours', models.CharField(blank=True, max_length=300)),
                ('services', models.TextField(blank=True)),
                ('source', models.URLField(blank=True)),
                ('osm_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_verified_at', models.DateTimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=250)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.localdate)),
                ('name', models.CharField(max_length=40)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'name'), name='metric_day_name')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('status', models.CharField(default='in_app', max_length=20)),
                ('error', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('photo', models.ImageField(blank=True, upload_to=care.models.private_path)),
                ('species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Horse', 'Horse'), ('Other', 'Other')], default='Dog', max_length=40)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('', 'Not recorded'), ('Female', 'Female'), ('Male', 'Male'), ('Unknown', 'Unknown')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('estimated_age', models.CharField(blank=True, max_length=80)),
                ('identification', models.CharField(blank=True, max_length=200)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('allergies', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preferred_vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care.provider')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weight', 'Weight'), ('treatment', 'Treatment'), ('vaccination', 'Vaccination'), ('medication', 'Medication'), ('observation', 'Observation'), ('visit', 'Vet visit'), ('document', 'Document')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(blank=True, upload_to=care.models.private_path)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='care.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Australia/Brisbane', max_length=80)),
                ('email_reminders', models.BooleanField(default=False)),
                ('reminder_hour', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(23)])),
                ('care_reminders', models.BooleanField(default=True)),
                ('supply_reminders', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new', 'New listing'), ('claim', 'Ownership claim'), ('correction', 'Correction')], max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('details', models.TextField(help_text='Include the address, website, services and supporting evidence. Never send identity documents or passwords.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('pack_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='tablets', max_length=40)),
                ('supplier_url', models.URLField(blank=True)),
                ('delivery_days', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(365)])),
                ('reorder_at', models.DecimalField(decimal_places=2, default=1, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('stock_updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='care.pet')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('worming', 'Worming'), ('flea', 'Flea & tick'), ('vaccination', 'Vaccination'), ('medication', 'Medication'), ('appointment', 'Appointment'), ('grooming', 'Grooming'), ('supply', 'Supply reorder'), ('other', 'Other care')], default='other', max_length=30)),
                ('due_at', models.DateTimeField()),
                ('repeat_days', models.PositiveIntegerField(default=0, help_text='0 for one-time; otherwise repeat every this many days, at the same local time.', validators=[django.core.validators.MaxValueValidator(3650)])),
                ('reminder_days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(365)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=400)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('units_used', models.DecimalField(decimal_places=2, default=0, help_text='Entered by you. No dose is suggested by the app.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='care.pet')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care.provider')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='care.supply')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='care.pet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
