# Generated by Django 5.2.17 on 2026-09-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='verification_evidence',
            field=models.TextField(blank=True, help_text='Record what was checked, the independent source and date. Required for verification.'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_task', to='care.healthrecord'),
        ),
    ]
