# Generated by Django 5.2.17 on 2026-09-26 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_provider_verification_evidence_task_source_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='stock_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
