# Generated by Django 5.2.17 on 2026-09-26 09:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_alter_supply_stock_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('', 'Still getting to know them'), ('gentle', 'Gentle, slower days'), ('balanced', 'A mix of play and rest'), ('busy', 'Always up for something')], max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pet',
            name='personality',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pet',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='social_comfort',
            field=models.CharField(blank=True, choices=[('', 'Not tried yet'), ('quiet', 'Prefers quiet spaces'), ('building', 'Building confidence'), ('social', 'Comfortable in busy places')], max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='support_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='training_level',
            field=models.CharField(blank=True, choices=[('', 'Not sure yet'), ('starting', 'Just starting'), ('basics', 'Learning the basics'), ('comfortable', 'Comfortable with everyday skills'), ('advanced', 'Advanced / sport experience')], max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='travel_comfort',
            field=models.CharField(blank=True, choices=[('', 'Not tried yet'), ('new', 'New to travelling'), ('learning', 'Getting comfortable'), ('confident', 'An experienced traveller')], max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='adventure_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='plan_step',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_offsets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_rule',
            field=models.CharField(blank=True, choices=[('', 'Use day interval below'), ('weekly', 'Every week'), ('monthly', 'Every month'), ('yearly', 'Every year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('worming', 'Worming'), ('flea', 'Flea & tick'), ('vaccination', 'Vaccination'), ('medication', 'Medication'), ('appointment', 'Appointment'), ('grooming', 'Grooming'), ('supply', 'Supply reorder'), ('training', 'Training'), ('sport', 'Sport & activities'), ('outing', 'Outing'), ('travel', 'Travel'), ('celebration', 'Celebration'), ('preparation', 'Plan preparation'), ('other', 'Other care')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='LifePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('template_key', models.CharField(max_length=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=400)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('confirmation', models.CharField(choices=[('idea', 'Idea / not booked'), ('enquired', 'Enquiry sent by me'), ('confirmed', 'Confirmed by me')], default='idea', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('reminder_offsets', models.JSONField(default=list)),
                ('creation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pets', models.ManyToManyField(related_name='life_plans', to='care.pet')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care.provider')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='care.lifeplan'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('plan__isnull', False)), fields=('plan', 'pet', 'plan_step'), name='unique_plan_pet_step'),
        ),
    ]
