# Generated by Django 5.2.17 on 2026-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_pet_energy_level_pet_goals_pet_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='pet_policy',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('vet', 'Veterinary care'), ('groomer', 'Grooming'), ('boarding', 'Boarding & day care'), ('sitter', 'Sitters & walkers'), ('trainer', 'Training'), ('shop', 'Pet supplies'), ('cafe', 'Dog-welcoming dining'), ('hotel', 'Pet-friendly stays'), ('park', 'Dog parks'), ('other', 'Other care')], max_length=20),
        ),
    ]
