# Generated by Django 5.2.17 on 2026-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_provider_pet_policy_alter_provider_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('vet', 'Veterinary care'), ('groomer', 'Grooming'), ('boarding', 'Boarding & day care'), ('sitter', 'Sitters & walkers'), ('trainer', 'Training'), ('shop', 'Pet supplies'), ('cafe', 'Dog-welcoming dining'), ('hotel', 'Pet-friendly stays'), ('park', 'Dog parks'), ('other', 'Other care'), ('shelter', 'Pounds & rescue'), ('charity', 'Charities & support'), ('funeral', 'Pet funerals & farewell care')], max_length=20),
        ),
    ]
