# Generated by Django 5.2.17 on 2026-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_alter_provider_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species_detail',
            field=models.CharField(blank=True, help_text='For example: cockatiel, bearded dragon, axolotl, goat or stick insect.', max_length=100, verbose_name='Type of animal'),
        ),
        migrations.AddField(
            model_name='provider',
            name='species_supported',
            field=models.JSONField(blank=True, default=list, help_text='Animal types explicitly recorded by the source, e.g. ["Horse", "Bird"]. Empty means unknown; never infer from the business name.'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Horse', 'Horse / pony'), ('Bird', 'Bird'), ('Reptile', 'Reptile'), ('Rabbit', 'Rabbit'), ('Guinea pig', 'Guinea pig'), ('Small mammal', 'Other small mammal'), ('Fish', 'Fish'), ('Amphibian', 'Amphibian'), ('Invertebrate', 'Invertebrate'), ('Farm animal', 'Farm companion'), ('Other', 'Another companion')], default='Dog', max_length=40),
        ),
    ]
