# Generated by Django 5.2.17 on 2026-09-26 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_pet_species_detail_provider_species_supported_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo_review_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo_status',
            field=models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Please choose another photo')], default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='SavedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.provider')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'provider'), name='one_saved_provider_per_owner')],
            },
        ),
    ]
