# Generated by Django 5.2.17 on 2026-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_pet_photo_review_note_pet_photo_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='avatar_key',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
