import React,{useState} from 'react';
import {View} from 'react-native';
import {router} from 'expo-router';
import {useApp} from '../state';
import type {Inventory} from '../types';
import {Button,Card,Chip,ErrorText,Field,Heading,Label,Screen,Title,s} from '../ui';
export default function InventoryScreen(){
 const app=useApp(),pet=app.selected;const [editing,setEditing]=useState<Inventory|'new'|null>(null),[error,setError]=useState('');
 if(app.loading)return <Screen><Label>Loading supplies…</Label></Screen>;
 if(!app.account||!pet)return <Screen><Title>Food & supplies</Title><Label>Add a pet to keep track of their food and treatment supply.</Label><Button title={app.account?'Add my pet':'Sign in'} onPress={()=>router.push(app.account?'/pet-editor':'/account')}/></Screen>;
 if(editing)return <InventoryEditor key={typeof editing==='string'?'new':editing.id} item={typeof editing==='string'?undefined:editing} onClose={()=>setEditing(null)}/>;
 const items=(app.account.inventory||[]).filter(i=>i.petId===pet.id);
 return <Screen><Title>{pet.name}’s supplies</Title><Button icon="chat" title="Tell Pip what we have" onPress={()=>router.push({pathname:'/pet-chat',params:{draft:`Help me keep track of ${pet.name}'s food and supplies.`}})}/><ErrorText message={error}/>{!items.length&&<Card><Heading>Start with their usual food</Heading><Label>Record what you have. Pip can estimate when you may need more.</Label><Button title="Add a supply" onPress={()=>setEditing('new')}/></Card>}{items.map(i=><Card key={i.id}><Heading>{i.product}</Heading><Label>{i.quantity===null?'Quantity not recorded':`${i.quantity} ${i.unit} recorded`}</Label>{i.estimate?.kind==='estimated'?<Label>Estimated {i.estimate.remaining} {i.unit} remaining · about {i.estimate.days} days</Label>:<Label small>{i.quantity===0?'No supply recorded.':'Add a daily amount for a food estimate, or link treatment stock to care.'}</Label>}<Label small muted>Recorded {new Date(i.quantityAt).toLocaleDateString('en-AU')}. Estimates can be corrected.</Label><View style={s.wrap}><Button secondary title="Correct supply" onPress={()=>setEditing(i)}/><Button secondary title="Record a purchase" onPress={()=>router.push({pathname:'/pet-chat',params:{draft:`I bought more ${i.product}. Help me record the purchase.`}})}/></View><Button secondary title="Add to shopping list" onPress={()=>router.push({pathname:'/pet-chat',params:{draft:`Add ${i.product} to my shopping list.`}})}/><Button secondary title="Remind me to restock" onPress={()=>router.push({pathname:'/pet-chat',params:{draft:`Help me plan a reorder reminder for ${i.product}, using my recorded supply.`}})}/><Button secondary title="Remove supply" onPress={()=>{void app.propose({action:'remove_inventory',petId:pet.id,data:{id:i.id}}).then(p=>router.push({pathname:'/review',params:{id:p.id}})).catch(e=>setError(e.message));}}/></Card>)}{!!items.length&&<Button title="Add a supply" icon="plus" onPress={()=>setEditing('new')}/>}<Button secondary title="My shopping lists" onPress={()=>router.push('/shopping')}/></Screen>;
}
function InventoryEditor({item,onClose}:{item?:Inventory;onClose:()=>void}){
 const app=useApp(),[product,setProduct]=useState(item?.product||''),[category,setCategory]=useState<Inventory['category']>(item?.category||'food'),[unit,setUnit]=useState<Inventory['unit']>(item?.unit||'g'),[amount,setAmount]=useState(item?.quantity?.toString()||''),[daily,setDaily]=useState(item?.dailyUse?.toString()||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){setBusy(true);setError('');try{const p=await app.propose({action:'save_inventory',petId:app.selected?.id,data:{...(item?{id:item.id}:{}),product,category,unit,quantity:amount===''?null:Number(amount),dailyUse:daily===''?null:Number(daily),quantityAt:new Date().toISOString()}});router.push({pathname:'/review',params:{id:p.id}});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Screen><Title>{item?'Correct supply':'Record supply'}</Title><Field label="Product" value={product} onChange={setProduct}/><View style={s.wrap}>{(['food','medication','treatment','supplement','other'] as const).map(c=><Chip key={c} title={c} active={category===c} onPress={()=>{setCategory(c);if(c==='medication'||c==='treatment')setDaily('');}}/>)}</View><Heading>Quantity unit</Heading><View style={s.wrap}>{(['g','kg','ml','tablets','doses','items'] as const).filter(u=>!item||u===item.unit).map(u=><Chip key={u} title={u} active={unit===u} onPress={()=>setUnit(u)}/>)}</View><Field label={`What is left today? (${unit}, optional)`} value={amount} onChange={setAmount} keyboardType="decimal-pad"/>{!['medication','treatment'].includes(category)&&<Field label={`Usual daily use (${unit}, optional)`} value={daily} onChange={setDaily} keyboardType="decimal-pad"/>}<Label small>Use your recorded amounts. Pip estimates supply; it does not recommend a dose or diet.</Label><ErrorText message={error}/><Button title="Review supply" busy={busy} onPress={()=>void save()}/><Button secondary title="Back to supplies" onPress={onClose}/></Screen>;
}
