import React, { useState, useEffect } from 'react';
import { ActivityIndicator, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useApp } from '../state';
import { Button, C, Card, ErrorText, Heading, Icon, Label, Screen, Title } from '../ui';
export default function Review() {
  const app=useApp();const {activeProposal,setActiveProposal}=app;const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const params=useLocalSearchParams<{id?:string;planKind?:string;planCategory?:string}>();
  const proposal=params.id?(app.activeProposal?.id===params.id?app.activeProposal:app.account?.proposals.find(p=>p.id===params.id)):(app.activeProposal||app.account?.proposals.at(-1));
  useEffect(()=>{if(proposal&&!params.id)router.setParams({id:proposal.id});},[proposal,params.id]);
  useEffect(()=>{if(proposal&&activeProposal?.id!==proposal.id)setActiveProposal(proposal);},[proposal,activeProposal?.id,setActiveProposal]);
  const [clock,setClock]=useState(()=>Date.now());
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),15000);return()=>clearInterval(timer);},[]);
  async function decide(value:'confirm'|'cancel'){if(!proposal)return;setBusy(true);setError('');try{await app.decide(proposal.id,value);}catch(e){setError((e as Error).message);}finally{setBusy(false);} }
  if(app.loading)return <Screen><ActivityIndicator color={C.ink}/></Screen>;
  if(!proposal)return <Screen><Title>No choice waiting</Title><Button title="Back to companion" onPress={()=>router.replace('/')}/></Screen>;
  const pending=proposal.status==='pending', expired=Date.parse(proposal.expiresAt)<=clock;
  function change(){if(!proposal)return; if(proposal.action==='set_supplies')router.push({pathname:'/supplies',params:{replace:proposal.id}});else if(proposal.action==='plan')router.push({pathname:'/plan',params:{replace:proposal.id,planKind:params.planKind,planCategory:params.planCategory}});else if(['add_pet','update_pet'].includes(proposal.action))router.push({pathname:'/pet-editor',params:{id:proposal.petId||'',replace:proposal.id}});else{app.setNotice('Cancel this choice, then choose another service or event.');router.back();}}
  return <Screen><View style={{alignSelf:'flex-start',padding:18,borderRadius:40,backgroundColor:C.sage}}><Icon name={proposal.status==='confirmed'?'check':'chat'} size={34}/></View><Title>{proposal.status==='confirmed'?(proposal.action==='remove_pet'?'Profile removed.':'All yours.'):proposal.status==='cancelled'?'No changes made.':expired?'This choice expired.':'Does this feel right?'}</Title>{proposal.action==='remove_pet'&&pending&&!expired&&<Label>There is no rush to make this choice. You can keep this profile if you are not ready to let it go.</Label>}<Card><Heading>{proposal.summary}</Heading>{proposal.details.map(([label,value],i)=><View key={i} style={{gap:3}}><Label small muted>{label}</Label><Label>{['When','Breakfast','Dinner','Next due','Completed at','Remind at','startAt'].includes(label)&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('en-AU'):value}</Label></View>)}</Card>{!!proposal.report&&<Label>{proposal.report}</Label>}<ErrorText message={error}/>{pending&&!expired?<><Label small muted>Nothing changes until you confirm. This choice is available for 30 minutes.</Label><Button title={proposal.action==='remove_pet'?'Permanently remove this profile':'Confirm'} icon="check" busy={busy} onPress={()=>void decide('confirm')}/>{['set_supplies','plan','add_pet','update_pet'].includes(proposal.action)&&<Button secondary title="Change" disabled={busy} onPress={change}/>}<Button secondary title={proposal.action==='remove_pet'?'Keep this profile':'Cancel'} disabled={busy} onPress={()=>void decide('cancel')}/></>:<Button title={['save_inventory','purchase_inventory','remove_inventory'].includes(proposal.action)?'Back to supplies':['set_pet_settings','set_pet_place'].includes(proposal.action)?'Back to pet profile':proposal.status==='confirmed'&&['plan','complete_event','record_care','update_event','cancel_event','snooze_event'].includes(proposal.action)?'See my calendar':proposal.action==='set_supplies'?'Back to my stores':proposal.action==='save_service'?'See my favourites':proposal.action==='remove_pet'?'Back to my pets':'Back to companion'} onPress={()=>{if(['save_inventory','purchase_inventory','remove_inventory'].includes(proposal.action)){router.replace('/inventory');return;}if(['set_pet_settings','set_pet_place'].includes(proposal.action)&&proposal.petId){router.replace({pathname:'/pet-editor',params:{id:proposal.petId}});return;}router.replace(proposal.status==='confirmed'&&['plan','complete_event','record_care','update_event','cancel_event','snooze_event'].includes(proposal.action)?'/calendar':proposal.action==='set_supplies'?'/supplies':proposal.action==='save_service'?'/account':proposal.action==='remove_pet'?'/pets':'/');}}/>}</Screen>;
}
