import React, { useState } from 'react';
import { Platform, Share, View } from 'react-native';
import { router } from 'expo-router';
import { useApp } from '../../state';
import { RememberSignIn, useRememberSignIn } from '../../RememberSignIn';
import { api } from '../../api';
import { Button, Card, Chip, ErrorText, Field, Heading, Label, Screen, Title, s } from '../../ui';
export default function AccountScreen() {
  const app=useApp();const [signup,setSignup]=useState(true),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState(false),[deletePassword,setDeletePassword]=useState('');
  const login=useRememberSignIn(setUsername,setSignup,app.account?.id);
  async function run(action:()=>Promise<void>){setError('');setBusy(true);try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function authenticate(){await app.authenticate(username.trim(),password,signup,login.remember);setPassword('');if(router.canGoBack())router.back();else router.replace('/');}
  async function exportData(){const data=await api('export');const json=JSON.stringify(data,null,2);if(Platform.OS==='web'){const url=URL.createObjectURL(new Blob([json],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='your-pet-care.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}else await Share.share({message:json,title:'Your Pet Care data'});}
  const reassurance=<Card><Heading>We&apos;re a team.</Heading><Label>Life gets busy, and sometimes it gets hard. That&apos;s okay. You don&apos;t have to remember everything on your own. We&apos;re here to help make caring for {app.selected?.name||'your pets'} a little easier, one day at a time.</Label></Card>;
  return <Screen><Title>{app.account?'Your space':'Make it yours'}</Title>{reassurance}<ErrorText message={error}/>{app.notice&&<Label>{app.notice}</Label>}{!app.account?<><Label>Browse freely. Sign in to keep your pets, conversations and plans together.</Label><View style={s.wrap}><Chip title="Create account" active={signup} onPress={()=>setSignup(true)}/><Chip title="Sign in" active={!signup} onPress={()=>setSignup(false)}/></View><Field autoComplete="username" label="Username" value={username} onChange={setUsername} placeholder="Letters, numbers, dots or underscores"/><Field autoComplete={signup?'new-password':'current-password'} label="Password" value={password} onChange={setPassword} secure placeholder="At least 12 characters"/><RememberSignIn value={login.remember} onChange={login.setRemember}/>{login.saved&&<Button secondary title="Forget saved sign-in name" onPress={()=>void run(login.forget)}/>}<Button title={signup?'Create account':'Sign in'} busy={busy} onPress={()=>void run(authenticate)}/><Label small muted>These are accounts for the new mobile app. Your earlier local web account has not been migrated.</Label></>:<><Card><Heading>{app.account.username}</Heading><Label>{app.account.pets.length} companions · {app.account.events.filter(e=>e.status==='planned').length} upcoming plans</Label><Button secondary title="Sign out" busy={busy} onPress={()=>void run(app.logout)}/></Card><Card><Heading>Supplies & savings</Heading><Label>{app.account.supplies?.stores.length?app.account.supplies.stores.map(s=>s.name).join(' ? '):'Keep your local pet shop and favourite supplies stores here.'}</Label><Button secondary title="My supplies stores" icon="food" onPress={()=>router.push('/supplies')}/></Card><Heading>Favourite places</Heading>{app.catalog.providers.filter(p=>app.account!.saved.includes(p.id)).map(p=><Button key={p.id} secondary title={p.name} onPress={()=>router.push({pathname:'/service',params:{id:p.id}})}/>)}{!app.account.saved.length&&<Label muted>Tap a place on the map and favourite it to keep it here.</Label>}<Button secondary title="Clear current conversation" onPress={()=>void run(app.clearChat)}/><Button secondary title="Export my data" onPress={()=>void run(exportData)}/>{!deleting?<Button secondary title="Delete my account" onPress={()=>setDeleting(true)}/>:<Card><Heading>Delete this account?</Heading><Label>This permanently removes this mobile account, pets, plans, saved places and conversations.</Label><Field label="Confirm your password" value={deletePassword} onChange={setDeletePassword} secure/><Button title="Permanently delete account" busy={busy} onPress={()=>void run(async()=>{await app.remove(deletePassword);setDeletePassword('');setDeleting(false);})}/><Button secondary title="Keep my account" onPress={()=>setDeleting(false)}/></Card>}</>}
  <Card><Heading>Companion connection</Heading><Label>{app.catalog.aiAvailable?'AI is connected. You choose when to share a message.':'The live AI agent is not connected yet.'}</Label><Label small muted>{app.online?'App service connected.':'Browsing the bundled directory. The app service is not connected.'}</Label><Button secondary title="Check connection" onPress={()=>void run(app.refresh)}/></Card><Button secondary title="Help & tutorials" icon="help" onPress={()=>router.push('/help')}/><Button secondary title="Privacy & your data" onPress={()=>router.push('/privacy')}/><Label small muted>Mobile development build · not yet submitted to either app store.</Label></Screen>;
}
