import {PipAssistant} from '../../PipAssistant';
import React,{useState} from 'react';
import {View} from 'react-native';
import {router} from 'expo-router';
import {useApp} from '../../state';
import {Button,Card,Chip,ErrorText,Heading,Label,Screen,Title,s} from '../../ui';
import {enableReminders} from '../../reminders';
import {CareTimeline} from '../../CareTimeline';
export default function Calendar(){
 const app=useApp(),[filter,setFilter]=useState('upcoming'),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[selectedDay,setSelectedDay]=useState<number|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const all=(app.account?.events||[]).filter(e=>filter==='completed'?e.status==='completed':e.status==='planned').sort((a,b)=>Date.parse(a.startAt)-Date.parse(b.startAt));
 const events=filter==='month'?all.filter(e=>{const d=new Date(e.startAt);return d.getMonth()===month.getMonth()&&d.getFullYear()===month.getFullYear()&&(!selectedDay||d.getDate()===selectedDay);}):all;
 async function reminders(){if(!app.account)return;try{await enableReminders(app.account);setNotice('Device reminders are on. Open the app regularly to refresh the next 50 reminders.');}catch(e){setError((e as Error).message);}}
 return <Screen wide><Title>Calendar</Title><PipAssistant scene="calendar" prompt="What shall we organise together?"/><View style={s.wrap}>{[['upcoming','Care timeline'],['completed','Completed'],['month','Month']].map(([id,title])=><Chip key={id} title={title} active={filter===id} onPress={()=>setFilter(id)}/>)}</View><Button secondary title="Add care or appointment" icon="plus" onPress={()=>router.push('/care-event')}/><ErrorText message={error}/>{!!notice&&<Label>{notice}</Label>}{filter==='month'&&<Card><Heading>{month.toLocaleDateString('en-AU',{month:'long',year:'numeric'})}</Heading><View style={s.wrap}><Button secondary title="Previous month" onPress={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()-1,1));setSelectedDay(null);}}/><Button secondary title="Next month" onPress={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()+1,1));setSelectedDay(null);}}/><Chip title="All dates" active={!selectedDay} onPress={()=>setSelectedDay(null)}/></View><View style={s.wrap}>{Array.from({length:new Date(month.getFullYear(),month.getMonth()+1,0).getDate()},(_,i)=>i+1).map(day=><Chip key={day} title={String(day)} active={selectedDay===day} onPress={()=>setSelectedDay(day)}/>)}</View><Label small>Shows saved care occurrences. Completing recurring care adds its next occurrence.</Label></Card>}<View testID="calendar-grid"><CareTimeline events={events}/></View>{!events.length&&<Card><Heading>{filter==='completed'?'Completed care will appear here':'Nothing coming up here yet'}</Heading><Label>Tell Pip about the next appointment or care task, or add one yourself.</Label><Button title="Talk with Pip" onPress={()=>router.push('/pet-chat')}/></Card>}{app.account&&<Button secondary title="Enable device reminders" icon="bell" onPress={()=>void reminders()}/>}</Screen>;
}
