import React, { useCallback, useMemo, useState } from 'react';
import { ScrollView, View } from 'react-native';
import * as Location from 'expo-location';
import { router, useLocalSearchParams } from 'expo-router';
import { useApp } from '../../state';
import ServiceMap from '../../ServiceMap';
import { Button, Card, Chip, ErrorText, Field, Heading, Icon, Label, Screen, Title, s } from '../../ui';
import { categoryIcon } from '../../catalog';
export default function MapScreen() {
  const app=useApp(),params=useLocalSearchParams<{category?:string}>();const [query,setQuery]=useState(''),[category,setCategory]=useState(params.category||''),[animal,setAnimal]=useState(''),[center,setCenter]=useState<{lat:number;lon:number}>(),[error,setError]=useState('');
  const providers=useMemo(()=>app.catalog.providers.filter(p=>(!category||p.category===category)&&(!animal||p.species_supported.includes(animal))&&`${p.name} ${p.address}`.toLowerCase().includes(query.toLowerCase())),[app.catalog.providers,category,animal,query]);
  const select=useCallback((id:string)=>router.push({pathname:'/service',params:{id}}),[]);
  async function locate(){try{const permission=await Location.requestForegroundPermissionsAsync();if(!permission.granted)throw new Error('Location is off. You can still search the directory.');const position=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setCenter({lat:position.coords.latitude,lon:position.coords.longitude});}catch(e){setError((e as Error).message);}}
  return <Screen><Title>Around you</Title><Field label="Find a place" value={query} onChange={setQuery} placeholder="Suburb, postcode or service name"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{[['','All'],['park','Parks'],['vet','Vets'],['cafe','Dining'],['hotel','Stays'],['sitter','Sitters'],['trainer','Training'],['shelter','Rescue'],['funeral','Farewell']].map(([value,label])=><Chip key={value} title={label} active={category===value} onPress={()=>setCategory(value)}/>)}</ScrollView><ScrollView horizontal contentContainerStyle={{gap:8}} showsHorizontalScrollIndicator={false}><Chip title="All animal coverage" active={!animal} onPress={()=>setAnimal('')}/>{app.catalog.species.map(sp=><Chip key={sp} title={sp} active={animal===sp} onPress={()=>setAnimal(sp)}/>)}</ScrollView><ServiceMap providers={providers} onSelect={select} center={center}/><Button secondary title="Use my location" icon="map" onPress={()=>void locate()}/><ErrorText message={error}/><Label small muted>{app.online?'Directory connected':'Offline directory copy'} · Animal filters show only coverage explicitly recorded by the source. Confirm suitability with the provider.</Label><View style={s.between}><Heading>{providers.length} places to explore</Heading></View>{providers.slice(0,40).map(p=><Card key={p.id}><View style={s.row}><Icon name={categoryIcon(p.category)} size={30}/><View style={{flex:1}}><Heading>{p.name}</Heading><Label small muted>{p.address||'Address details not recorded'}</Label></View></View><Button secondary title={`Explore ${p.name}`} onPress={()=>select(p.id)}/></Card>)}{providers.length>40&&<Label small muted>Showing the first 40 results below. All matching results are on the map; narrow your search to see more detail.</Label>}{!providers.length&&<Card><Label>No matches in this directory copy. Try a nearby suburb or clear the animal filter.</Label></Card>}<Label small muted>Map and directory data © OpenStreetMap contributors. Listings are not live opening-hours or booking information.</Label></Screen>;
}
