export type Pet = { id: string; name: string; species: string; breed: string; age: string; social: string; training: string; goals: string; careNotes?:string; careSettings?:Record<string,Record<string,string>>; favouritePlaceIds?:string[]; preferredVetId?:string; mealRoutine?:{breakfastAt:string;dinnerAt:string} };
export type Event = { id: string; petId: string; title: string; startAt: string; minutes: number; repeatDays: number; location: string; status: 'planned' | 'completed' | 'cancelled' };
export type Provider = { id: string; name: string; category: string; address: string; lat: number; lon: number; website: string; phone: string; source: string; species_supported: string[]; pet_policy: string };
export type ProposalInput = { action: 'set_pet_settings' | 'set_pet_place' | 'add_shopping_items' | 'remove_pet' | 'set_supplies' | 'add_pet' | 'update_pet' | 'plan' | 'save_service' | 'set_preferred_vet' | 'set_meal_routine' | 'stop_meal_routine' | 'complete_event'; petId?: string | null; data: Record<string, unknown>; replaceId?: string };
export type Proposal = ProposalInput & { id: string; summary: string; details: [string,string][]; status: string; expiresAt: string; resultId?: string; report?:string };
export type Message = { sources?:{url:string;title:string}[]; researchedAt?:string; savedShoppingListId?:string; shoppingSuggestions?:{name:string;reason:string}[]; role: 'user' | 'assistant'; content: string; navigation?:{screen:'map';mode:'walk';minutes?:number;stop?:'none'|'rest'|'cafe'|'friends'}|{screen:'map';mode:'places';category:string} };
export type MapPoint = {lat:number;lon:number};
export type WalkRoute = {id:string;distance:number;minutes:number;geometry:{type:'LineString';coordinates:[number,number][]}};
export type ShoppingList={id:string;name:string};
export type ShoppingItem = {id:string;listId?:string;name:string;store:string;done:boolean};
export type ShoppingChange = {action:'create_list';name:string}|{action:'rename_list';listId:string;name:string}|{action:'delete_list';listId:string}|{action:'add';name:string;store:string;listId?:string}|{action:'check';id:string;done:boolean;listId?:string}|{action:'remove';id:string;listId?:string};
export type AttentionItem = {id:string;kind:'choice'|'event';petId:string|null;title:string;targetId:string;at:string};
export type Account = { attention?:AttentionItem[]; shopping?:ShoppingItem[]; shoppingLists?:ShoppingList[]; id: string; username: string; supplies?: SupplyPreferences; pets: Pet[]; events: Event[]; saved: string[]; proposals: Proposal[]; messages: Record<string, Message[]> };
export type Catalog = { providers: Provider[]; supplyStores?:SupplySource[]; species: string[]; aiAvailable: boolean; weatherAvailable: boolean; crowdsAvailable: boolean };

export type SupplyPreferences={stores:{name:string;website:string;address?:string;providerId?:string}[];saleAlerts:boolean};
export type SupplySource={id:string;name:string;website:string;offersUrl:string;label:string;verifiedAt:string};
export type SupplyOffer={id:string;storeId:string;storeName:string;title:string;url:string;source:string;datesKnown:boolean};
export type SupplyFeed={storeId:string;status:'connected'|'unavailable';checkedAt:string;offers:SupplyOffer[]};
