from django.contrib import admin
from django.urls import path, include
from care import views
from care import discovery
from care import life
from care import journey
from care import membership
from care import photos, companion

urlpatterns = [
    path('companion/', companion.companion, name='companion'),
    path('companion/pets/<int:pk>/propose/', companion.propose, name='companion-propose'),
    path('companion/proposals/<uuid:pk>/', companion.review, name='companion-review'),
    path('companion/proposals/<uuid:proposal_pk>/change/', companion.propose, name='companion-change'),
    path('companion/proposals/<uuid:pk>/decide/', companion.decide, name='companion-decide'),
    path('pets/<int:pk>/picture/', photos.choose_picture, name='pet-picture'),
    path('pets/<int:pk>/photo/', photos.upload_photo, name='pet-photo'),
    path('cookies/', membership.cookies, name='cookies'),
    path('services/saved/', membership.saved_services, name='saved-services'),
    path('providers/<int:pk>/save/', membership.save_service, name='save-service'),
    path('admin/', admin.site.urls),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', journey.home, name='home'),
    path('today/', views.home, name='overview'),
    path('journey/', journey.conversation, name='journey'),
    path('preview/reset/', journey.reset_preview, name='preview-reset'),
    path('journey/ideas/', journey.ready, name='journey-ready'),
    path('journey/plan/<str:key>/', journey.quick_plan, name='quick-plan'),
    path('community/', journey.community, name='community'),
    path('community/<str:category>/', journey.community, name='community-category'),
    path('services/add/', journey.offer_service, name='offer-service'),
    path('services/thanks/<int:pk>/', journey.service_thanks, name='service-thanks'),
    path('pets/', views.pets, name='pets'),
    path('pets/add/', views.edit, {'kind': 'pet'}, name='pet-add'),
    path('pets/<int:pk>/', views.pet_detail, name='pet-detail'),
    path('pets/<int:pk>/edit/', views.edit, {'kind': 'pet'}, name='pet-edit'),
    path('pets/<int:pk>/personality/', life.personality, name='pet-personality'),
    path('life/', life.life_home, name='life'),
    path('plans/new/<str:template_key>/', life.plan_edit, name='plan-add'),
    path('plans/<int:pk>/', life.plan_detail, name='plan-detail'),
    path('plans/<int:pk>/edit/', life.plan_edit, name='plan-edit'),
    path('plans/<int:pk>/action/', life.plan_action, name='plan-action'),
    path('reminders/', views.reminders, name='reminders'),
    path('calendar/', views.care_calendar, name='calendar'),
    path('calendar/export/', views.calendar_export, name='calendar-export'),
    path('tasks/add/', views.edit, {'kind': 'task'}, name='task-add'),
    path('tasks/<int:pk>/edit/', views.edit, {'kind': 'task'}, name='task-edit'),
    path('tasks/<int:pk>/action/', views.task_action, name='task-action'),
    path('supplies/', views.supplies, name='supplies'),
    path('supplies/add/', views.edit, {'kind': 'supply'}, name='supply-add'),
    path('supplies/<int:pk>/edit/', views.edit, {'kind': 'supply'}, name='supply-edit'),
    path('supplies/<int:pk>/action/', views.supply_action, name='supply-action'),
    path('records/add/', views.edit, {'kind': 'record'}, name='record-add'),
    path('records/<int:pk>/edit/', views.edit, {'kind': 'record'}, name='record-edit'),
    path('files/<str:kind>/<int:pk>/', views.private_file, name='private-file'),
    path('find-care/', discovery.find_care, name='find-care'),
    path('providers/<int:pk>/', discovery.provider_detail, name='provider'),
    path('providers/<int:pk>/attach/', discovery.attach_provider, name='attach-provider'),
    path('providers/<int:pk>/contact/', discovery.contact_provider, name='contact-provider'),
    path('business/submit/', views.listing_request, name='listing-request'),
    path('business/requests/', views.my_requests, name='my-requests'),
    path('settings/', views.settings_view, name='settings'),
    path('settings/export/', views.export_data, name='export-data'),
    path('settings/delete/', views.delete_account, name='delete-account'),
    path('privacy/', views.privacy, name='privacy'),
]
