"""Front-door destinations. Every tile is a normal link, with decorative motion."""
ITEMS = [
    ('pets', 'My pets', '/pets/', 'Your favourite little characters', 'peach'),
    ('sports', 'Activities', '/life/?category=sports', 'Catch a little adventure', 'mint'),
    ('training', 'Training', '/life/?category=training', 'Small wins, happy tails', 'lilac'),
    ('cafe', 'Cafés & dining', '/life/?category=cafes', 'A table for you and your best friend', 'butter'),
    ('hotel', 'Pet-friendly stays', '/life/?category=stays', 'Dream somewhere new', 'blue'),
    ('road', 'Road trips', '/life/?category=roadtrips', 'Windows down, adventure ahead', 'rose'),
    ('flight', 'Flying together', '/life/?category=flying', 'Get ready for take-off', 'blue'),
    ('outdoors', 'Parks & outdoors', '/life/?category=outdoors', 'Follow a new sniff', 'mint'),
    ('play', 'Play & enrichment', '/life/?category=enrichment', 'Make room for a little fun', 'peach'),
    ('birthday', 'Little milestones', '/life/?category=milestones', 'Celebrate their little life', 'lilac'),
    ('calendar', 'Our calendar', '/calendar/', 'Something to look forward to', 'butter'),
    ('bell', 'Reminders', '/reminders/', 'A little nudge, then back to life', 'rose'),
    ('vet', 'Find care', '/find-care/', 'Good people, close by', 'mint'),
    ('health', 'Health & records', '/records/add/', 'Keep their story together', 'blue'),
    ('bowl', 'Food & supplies', '/supplies/', 'Keep the good stuff coming', 'butter'),
    ('walk', 'Dog walking', '/community/help/', 'A walk makes a good day', 'peach'),
    ('sitting', 'Pet sitting', '/community/help/', 'Company when you’re away', 'lilac'),
    ('rescue', 'Pounds & rescue', '/community/rescue/', 'A new home, or a way home', 'mint'),
    ('giving', 'Charities', '/community/giving/', 'Share a little love', 'rose'),
    ('farewell', 'Saying goodbye', '/community/farewell/', 'Gentle support, at your pace', 'sand'),
    ('service', 'Share your service', '/services/add/', 'Put your caring hands up', 'butter'),
    ('community', 'Community', '/community/', 'A whole world of pet people', 'blue'),
    ('care', 'Everyday care', '/today/', 'The little things, looked after', 'peach'),
    ('settings', 'Preferences', '/settings/', 'Make yourself at home', 'lilac'),
]
